import React, { useCallback, useEffect, useRef, useState } from 'react';
import { Alert, AppState, FlatList, KeyboardAvoidingView, Linking, Pressable, ScrollView, Text, View } from 'react-native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { z } from 'zod';
import * as Updates from 'expo-updates';
import { useWorkspace } from '../domain/store';
import { attachmentSchema, memberSchema, type Attachment, type Message } from '../domain/contracts';
import { updateDecision } from '../domain/updates';
import { Runtime } from '../data/runtime';
import { errorText } from '../data/client';
import { Transfers } from '../data/transfers';
import { config, installed, loginTarget } from '../platform/config';
import { cache } from '../platform/storage';
import { enableNotifications } from '../platform/notifications';
import { useTheme } from '../ui/theme';
import { Button, Empty, Input, Label, Loading, Notice, styles } from '../ui/components';

export function LoginScreen({runtime}:{runtime:Runtime}){const [origin,setOrigin]=useState(config.apiOrigin);const [busy,setBusy]=useState(false);const [error,setError]=useState('');const t=useTheme();return <ScrollView contentContainerStyle={[styles.content,{flexGrow:1,justifyContent:'center',backgroundColor:t.bg}]} keyboardShouldPersistTaps="handled"><Text style={{fontSize:30,fontWeight:'700',color:t.text}}>DualLane</Text><Label>共享空间 · 聊天和文件会保存到服务器</Label><Input accessibilityLabel="服务地址或邀请链接" autoCapitalize="none" autoCorrect={false} keyboardType="url" placeholder="HTTPS 服务地址或空间邀请链接" value={origin} onChangeText={setOrigin}/><Label muted>需要已有成员邀请后才能进入。</Label><Button title={busy?'正在登录…':'使用 GitHub 登录'} disabled={busy||!origin} onPress={()=>{setBusy(true);setError('');void Promise.resolve().then(()=>{const target=loginTarget(origin);return runtime.login(target.origin,target.inviteCode);}).catch(e=>setError(errorText(e))).finally(()=>setBusy(false));}}/><Notice text={error}/></ScrollView>;}
export function ConversationsScreen({open}:{open:(id:string)=>void}){const conversations=useWorkspace(s=>s.conversations);const connection=useWorkspace(s=>s.connection);const [query,setQuery]=useState('');const t=useTheme();const items=Object.values(conversations).filter(c=>c.displayTitle.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.lastActivityAt.localeCompare(a.lastActivityAt));return <View style={[styles.page,{backgroundColor:t.bg}]}><View style={styles.content}><Input accessibilityLabel="筛选会话" placeholder="筛选会话" value={query} onChangeText={setQuery}/><Label muted>{connection}</Label></View><FlatList data={items} keyExtractor={c=>c.id} ListEmptyComponent={<Empty text="还没有会话，可以从成员列表发起私聊。"/>} renderItem={({item})=><Pressable accessibilityRole="button" accessibilityLabel={`打开${item.displayTitle}，${item.unreadCount}条未读`} onPress={()=>open(item.id)} style={[styles.row,{borderColor:t.line,backgroundColor:t.surface}]}><Text style={[styles.title,{color:t.text}]}>{item.displayTitle}{item.unreadCount>0?` · ${Math.min(item.unreadCount,99)}${item.unreadCount>99?'+':''}`:''}</Text><Text numberOfLines={1} style={{color:t.muted}}>{item.lastMessagePlainText||'还没有消息'}</Text></Pressable>}/></View>;}
export function MessageRow({message,retry,download}:{message:Message;retry:()=>void;download:(file:Attachment)=>void}){const t=useTheme();const userId=useWorkspace(s=>s.bootstrap?.auth.currentUser.id);const own=message.authorId===userId;return <View style={{paddingHorizontal:16,paddingVertical:6,alignItems:own?'flex-end':'flex-start'}}><Text style={{color:t.muted,fontSize:12,marginBottom:4}}>{message.authorName} · {new Date(message.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</Text><View style={{maxWidth:'90%',padding:12,borderRadius:16,backgroundColor:own?t.sharedSoft:t.surface}}><Text selectable style={{fontSize:16,lineHeight:25,color:t.text}}>{message.plainText}</Text>{message.fallback&&<Label muted>部分内容暂不支持，可在“我的”检查更新。</Label>}{message.attachments.map(file=><FileRow key={file.id} file={file} download={()=>download(file)}/>)}{message.status==='sending'&&<Label muted>发送中…</Label>}{message.status==='failed'&&<><Notice text={message.error??'发送失败'}/><Button title="重试发送" secondary onPress={retry}/></>}</View></View>;}
export function ChatScreen({id,runtime,transfers,details}:{id:string;runtime:Runtime;transfers:Transfers;details:()=>void}){
  const t=useTheme(),insets=useSafeAreaInsets();const conversation=useWorkspace(s=>s.conversations[id]);const messages=useWorkspace(s=>s.messages[id]??emptyMessages);const draft=useWorkspace(s=>s.drafts[id]??'');const [loading,setLoading]=useState(true),[error,setError]=useState(''),[hasOlder,setHasOlder]=useState(true),[progress,setProgress]=useState('');const list=useRef<FlatList<Message>>(null);const nearBottom=useRef(true);const [newMessages,setNewMessages]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{await runtime.open(id);}catch(e){setError(errorText(e));}finally{setLoading(false);}},[id,runtime]);useEffect(()=>{void load();},[load]);
  useEffect(()=>{if(nearBottom.current)list.current?.scrollToEnd({animated:false});else setNewMessages(true);const last=messages.at(-1);if(last&&!last.status&&nearBottom.current&&AppState.currentState==='active')void runtime.markRead(id,last.id).catch(()=>undefined);},[messages,id,runtime]);
  const send=(existing?:Message)=>{setError('');nearBottom.current=true;void runtime.send(id,draft,existing).catch(e=>setError(errorText(e)));};
  return <KeyboardAvoidingView behavior="padding" style={[styles.page,{backgroundColor:t.bg}]}><View style={{paddingHorizontal:16,paddingVertical:8,flexDirection:'row',alignItems:'center',justifyContent:'space-between'}}><Text style={{fontSize:18,fontWeight:'600',color:t.text,flex:1}} numberOfLines={1}>{conversation?.displayTitle??'会话'}</Text><Button title="详情" secondary onPress={details}/></View><Notice text={error||progress}/>{loading&&<Loading/>}<FlatList ref={list} data={messages} keyExtractor={m=>m.id} keyboardShouldPersistTaps="handled" onScroll={e=>{const {contentOffset,layoutMeasurement,contentSize}=e.nativeEvent;nearBottom.current=contentSize.height-contentOffset.y-layoutMeasurement.height<100;if(nearBottom.current)setNewMessages(false);}} scrollEventThrottle={100} onContentSizeChange={()=>{if(nearBottom.current)list.current?.scrollToEnd({animated:false});}} ListHeaderComponent={hasOlder&&messages.length>0?<Button title="加载更早消息" secondary onPress={()=>{void runtime.messages(id,messages[0]?.id).then(count=>setHasOlder(count===50)).catch(e=>setError(errorText(e)));}}/>:null} ListEmptyComponent={!loading?<Empty text="还没有消息"/>:null} renderItem={({item})=><MessageRow message={item} retry={()=>send(item)} download={file=>{const api=runtime.api;if(api)void transfers.download(api,useWorkspace.getState().accountKey,file).catch(e=>setError(errorText(e)));}}/>}/>{newMessages&&<Button title="回到最新" secondary onPress={()=>{nearBottom.current=true;setNewMessages(false);list.current?.scrollToEnd();}}/>}{conversation?.capabilities.canSendMessage?<View style={{padding:12,paddingBottom:Math.max(insets.bottom,12),gap:8}}><Input accessibilityLabel="消息" multiline placeholder="发送消息" value={draft} onChangeText={text=>runtime.draft(id,text)} style={{maxHeight:140}}/><View style={styles.actions}><Button title="文件" secondary disabled={!conversation.capabilities.canUploadFile||!!progress} onPress={()=>{const api=runtime.api,key=useWorkspace.getState().accountKey;if(!api)return;void transfers.choose(key,id).then(async task=>{if(!task)return;setProgress('准备上传…');const file=await transfers.run(api,key,task,n=>setProgress(`上传 ${Math.round(n*100)}%`));if(file)await runtime.send(id,'',undefined,file.id);}).catch(e=>setError(errorText(e))).finally(()=>setProgress(''));}}/><Button title="发送" disabled={!draft.trim()} onPress={()=>send()}/></View></View>:<Empty text="当前会话不可发送消息"/>}</KeyboardAvoidingView>;
}
const emptyMessages:Message[]=[];
export function DetailsScreen({id,runtime}:{id:string;runtime:Runtime}){const c=useWorkspace(s=>s.conversations[id]);const t=useTheme();const [error,setError]=useState('');return <ScrollView style={{backgroundColor:t.bg}} contentContainerStyle={styles.content}><Text style={[styles.section,{color:t.text}]}>{c?.displayTitle}</Text><Label>{c?.retentionText}</Label><Label muted>共享空间会保存聊天和文件。</Label><Label>消息提醒</Label><View style={styles.actions}>{(['all','mentions','muted'] as const).map((level,i)=><Button key={level} title={['所有消息','仅提到我','免打扰'][i]??level} secondary={c?.notificationLevel!==level} onPress={()=>void runtime.notification(id,level).catch(e=>setError(errorText(e)))}/>)}</View><Notice text={error}/><Label>会话成员</Label>{c?.members.map(m=><Label key={m.id}>{m.displayName}</Label>)}</ScrollView>;}
export function FilesScreen({runtime,transfers}:{runtime:Runtime;transfers:Transfers}){const t=useTheme();const files=useWorkspace(s=>s.files);const key=useWorkspace(s=>s.accountKey);const permission=useWorkspace(s=>s.bootstrap?.permissions.canUpload);const [query,setQuery]=useState(''),[error,setError]=useState(''),[progress,setProgress]=useState(''),[revision,setRevision]=useState(0);const refresh=async()=>{if(!runtime.api)return;const r=await runtime.api.json(`/api/workspace/files?q=${encodeURIComponent(query)}`,z.object({files:z.array(attachmentSchema)}));useWorkspace.setState({files:r.files});};const run=async(task:ReturnType<Transfers['tasks']>[number])=>{if(!runtime.api)return;setProgress('上传中');try{await transfers.run(runtime.api,key,task,n=>setProgress(`上传 ${Math.round(n*100)}%`));await refresh();}catch(e){setError(errorText(e));}finally{setProgress('');setRevision(v=>v+1);}};return <ScrollView style={{backgroundColor:t.bg}} contentContainerStyle={styles.content}><Input accessibilityLabel="查找文件" placeholder="查找文件" value={query} onChangeText={setQuery}/><View style={styles.actions}><Button title="搜索" secondary onPress={()=>void refresh().catch(e=>setError(errorText(e)))}/><Button title="上传文件" disabled={!permission||!!progress} onPress={()=>void transfers.choose(key).then(task=>task&&run(task)).catch(e=>setError(errorText(e)))}/></View><Notice text={error||progress}/>{files.filter(f=>f.fileName.includes(query)).map(file=><FileRow key={file.id} file={file} download={()=>{if(runtime.api)void transfers.download(runtime.api,key,file).catch(e=>setError(errorText(e)));}}/>)}{!files.length&&<Empty text="还没有文件"/>}<Text style={{color:t.muted}}>上传任务</Text><View key={revision}>{transfers.tasks(key).filter(task=>!task.complete).map(task=><View key={task.id} style={{gap:8,paddingVertical:8}}><Label>{task.fileName}</Label><View style={styles.actions}><Button title="继续" secondary disabled={!!progress} onPress={()=>void run(task)}/><Button title="暂停" secondary onPress={()=>transfers.pause(task.id)}/><Button title="取消" secondary disabled={!!progress} onPress={()=>{if(runtime.api)void transfers.cancel(runtime.api,key,task).then(()=>setRevision(v=>v+1)).catch(e=>setError(errorText(e)));}}/></View></View>)}</View></ScrollView>;}
function FileRow({file,download}:{file:Attachment;download:()=>void}){const t=useTheme();return <View style={[styles.row,{borderColor:t.line}]}><Text numberOfLines={2} style={{color:t.text,fontSize:16}}>{file.fileName}</Text><Label muted>{Math.ceil(file.byteSize/1024)} KB · {file.status==='available'?'可下载':'暂不可用'}</Label><Button title="下载并保存" secondary disabled={!file.capabilities.canDownload} onPress={download}/></View>;}
export function MembersScreen({runtime,open}:{runtime:Runtime;open:(id:string)=>void}){const members=useWorkspace(s=>s.bootstrap?.members??[]);const [items,setItems]=useState(members),[query,setQuery]=useState(''),[error,setError]=useState('');const t=useTheme();return <View style={[styles.page,{backgroundColor:t.bg}]}><View style={styles.content}><Input accessibilityLabel="查找成员" placeholder="查找成员" value={query} onChangeText={setQuery}/><Button title="搜索" secondary onPress={()=>{if(runtime.api)void runtime.api.json(`/api/workspace/members?q=${encodeURIComponent(query)}`,z.object({members:z.array(memberSchema)})).then(r=>setItems(r.members)).catch(e=>setError(errorText(e)));}}/><Notice text={error}/></View><FlatList data={items} keyExtractor={m=>m.id} ListEmptyComponent={<Empty text="当前范围内没有匹配成员"/>} renderItem={({item})=><View style={[styles.row,{borderColor:t.line}]}><Label>{item.displayName}{item.kind==='bot'?' · Bot':''}</Label>{item.capabilities.canStartDirectConversation&&<Button title="发起私聊" secondary onPress={()=>void runtime.direct(item.id).then(open).catch(e=>setError(errorText(e)))}/>}</View>}/></View>;}
export function AccountScreen({runtime,mode,setMode}:{runtime:Runtime;mode:'system'|'light'|'dark';setMode:(mode:'system'|'light'|'dark')=>void}){const b=useWorkspace(s=>s.bootstrap),p=useWorkspace(s=>s.policy);const t=useTheme();const [notice,setNotice]=useState(''),[otaReady,setOtaReady]=useState(false);return <ScrollView style={{backgroundColor:t.bg}} contentContainerStyle={styles.content}><Text style={[styles.section,{color:t.text}]}>{b?.auth.currentUser.displayName}</Text><Label>{b?.space.name}</Label><Label muted>今日剩余传输 {Math.round((b?.policy.remainingQuotaBytes??0)/1048576)} MiB</Label><Label muted>消息保留上限 {b?.policy.messageRetentionCount} 条</Label><Label>外观</Label><View style={styles.actions}>{(['system','light','dark'] as const).map((value,i)=><Button key={value} title={['跟随系统','浅色','深色'][i]??value} secondary={mode!==value} onPress={()=>{setMode(value);cache.set('appearance',value);}}/>)}</View><Label>通知</Label><Label muted>普通后台收到新消息时显示通知。休眠或进程结束后可能延迟，重新打开应用会同步。</Label><Button title="开启消息通知" onPress={()=>Alert.alert('消息通知','允许 DualLane 在后台收到消息时显示系统通知。',[{text:'暂不开启',style:'cancel'},{text:'继续',onPress:()=>void enableNotifications().then(granted=>setNotice(granted?'通知已开启':'通知未开启，可在系统设置中修改'))}])}/><Button title="系统通知设置" secondary onPress={()=>void Linking.openSettings()}/><Notice text={notice}/><Label>版本 {installed.appVersion} ({installed.versionCode})</Label><Button title="检查更新" secondary onPress={()=>void runtime.checkPolicy()}/>{p&&<><Label muted>{p.latest.releaseNotes.join('\n')||'暂无更新说明'}</Label>{p.apkUrl&&<Button title="下载 Android 安装包" onPress={()=>void Linking.openURL(p.apkUrl!)}/>}</>}<Button title="检查兼容补丁" secondary disabled={!Updates.isEnabled} onPress={()=>{void Updates.checkForUpdateAsync().then(async result=>{if(result.isAvailable){await Updates.fetchUpdateAsync();setOtaReady(true);setNotice('补丁已验证，下次启动生效');}else setNotice('当前补丁已是最新');}).catch(()=>setNotice('补丁验证或下载失败，继续使用当前版本'));}}/>{otaReady&&<Button title="保存草稿并重启" onPress={()=>void Updates.reloadAsync()}/>}<Button title="重新连接" secondary onPress={()=>void runtime.resume()}/><Button title="退出登录" secondary onPress={()=>Alert.alert('退出登录','本机缓存和未发送草稿将清除。',[{text:'取消',style:'cancel'},{text:'退出',style:'destructive',onPress:()=>void runtime.logout()}])}/></ScrollView>;}
export function UpdatePrompt({runtime}:{runtime:Runtime}){const policy=useWorkspace(s=>s.policy);const [deferred,setDeferred]=useState('');const t=useTheme();if(!policy)return null;const decision=updateDecision(policy,installed);const dismissed=z.number().catch(0).parse(cache.get(`defer:${policy.latest.releaseId}`)??0);if(decision==='none'||(decision!=='forced'&&(deferred===policy.latest.releaseId||dismissed>Date.now())))return null;return <View accessibilityViewIsModal={decision==='forced'} style={{padding:16,gap:12,backgroundColor:t.surface}}><Text style={{fontSize:18,fontWeight:'600',color:t.text}}>{decision==='forced'?'请更新后继续使用':decision==='strong'?'建议尽快更新':'发现新版本'}</Text><Label>{policy.latest.releaseNotes.join('\n')||`可用版本 ${policy.latest.appVersion}`}</Label>{policy.apkUrl?<Button title="下载更新" onPress={()=>void Linking.openURL(policy.apkUrl!)}/>:<Label muted>安装包暂未发布，请联系空间维护者。</Label>}<Button title="重新检查" secondary onPress={()=>void runtime.checkPolicy()}/>{decision!=='forced'&&<Button title="稍后提醒" secondary onPress={()=>{cache.set(`defer:${policy.latest.releaseId}`,Date.now()+86400000);setDeferred(policy.latest.releaseId);}}/>}</View>;}
