import React, { useCallback, useEffect, useLayoutEffect, useRef, useState } from 'react';
import { AppState, FlatList, KeyboardAvoidingView, Linking, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { useNavigation } from '@react-navigation/native';
import { useSafeAreaInsets } from 'react-native-safe-area-context';
import { z } from 'zod';
import { useWorkspace } from '../domain/store';
import { attachmentSchema, memberSchema, type Attachment, type Message } from '../domain/contracts';
import { updateDecision } from '../domain/updates';
import { Runtime } from '../data/runtime';
import { errorText } from '../data/client';
import { Transfers } from '../data/transfers';
import { config, installed, loginTarget } from '../platform/config';
import { cache } from '../platform/storage';
import { useTheme } from '../ui/theme';
import { AppHeader, Button, ConversationRow, Empty, EmptyState, InlineFeedback, Input, Label, Loading, Notice, SegmentedControl, styles } from '../ui/components';

export function LoginScreen({runtime}:{runtime:Runtime}){
  const [destination,setDestination]=useState('');const [busy,setBusy]=useState(false);const [error,setError]=useState('');const t=useTheme();
  const configured=Boolean(config.apiOrigin);
  const login=async()=>{
    setError('');let target:ReturnType<typeof loginTarget>;
    try{target=loginTarget(destination,config.apiOrigin);}
    catch{setError(configured?'请使用当前服务的有效空间邀请链接':'请输入有效的 HTTPS 服务地址或空间邀请链接');return;}
    setBusy(true);
    try{await runtime.login(target.origin,target.inviteCode);}
    catch(e){setError(errorText(e));}
    finally{setBusy(false);}
  };
  return <ScrollView contentContainerStyle={[styles.content,{flexGrow:1,justifyContent:'center',backgroundColor:t.bg}]} keyboardShouldPersistTaps="handled"><Text style={{fontSize:t.type.title,fontWeight:'700',color:t.text}}>DualLane</Text><Label>共享空间 · 聊天和文件会保存到空间</Label><Input accessibilityLabel={configured?'空间邀请链接（可选）':'服务地址或邀请链接'} autoCapitalize="none" autoCorrect={false} keyboardType="url" placeholder={configured?'空间邀请链接（已有账号可直接登录）':'HTTPS 服务地址或空间邀请链接'} value={destination} onChangeText={setDestination}/><Label muted>已有账号可直接登录。邀请仅用于加入当前服务的空间。</Label><Button title={busy?'正在登录…':'使用 GitHub 登录'} disabled={busy||(!configured&&!destination.trim())} onPress={()=>void login()}/><Notice text={error}/></ScrollView>;
}
export function ConversationsScreen({open}:{open:(id:string)=>void}){
  const conversations=useWorkspace(s=>s.conversations);const connection=useWorkspace(s=>s.connection);const selfId=useWorkspace(s=>s.bootstrap?.auth.currentUser.id);
  const [query,setQuery]=useState('');const [list,setList]=useState<'conversations'|'topics'>('conversations');const t=useTheme();
  const items=Object.values(conversations).filter(c=>c.displayTitle.toLowerCase().includes(query.toLowerCase())).sort((a,b)=>b.lastActivityAt.localeCompare(a.lastActivityAt));
  return <View style={[styles.page,{backgroundColor:t.bg}]}><AppHeader title="聊天" subtitle={connection==='已连接'?undefined:connection} includeTopInset/><View style={styles.content}><SegmentedControl accessibilityLabel="会话与话题" value={list} options={[{value:'conversations',label:'会话'},{value:'topics',label:'话题'}]} onChange={setList}/>{list==='conversations'?<Input accessibilityLabel="筛选已加载的会话" placeholder="筛选已加载的会话" value={query} onChangeText={setQuery}/>:null}</View>{list==='topics'?<EmptyState title="话题列表稍后接入" detail="这一栏承接 Web 的话题入口。当前不会从这里加入、发送或把群草稿带到话题。"/>:<FlatList data={items} keyExtractor={c=>c.id} ListEmptyComponent={<Empty text="还没有会话，可以从成员列表发起私聊。"/>} renderItem={({item})=><ConversationRow conversation={item} selfId={selfId} onPress={()=>open(item.id)}/>}/>}</View>;
}
export function MessageRow({message,retry,download}:{message:Message;retry:()=>void;download:(file:Attachment)=>void}){const t=useTheme();const userId=useWorkspace(s=>s.bootstrap?.auth.currentUser.id);const own=message.authorId===userId;return <View style={{paddingHorizontal:16,paddingVertical:6,alignItems:own?'flex-end':'flex-start'}}><Text style={{color:t.muted,fontSize:12,marginBottom:4}}>{message.authorName} · {new Date(message.createdAt).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit'})}</Text><View style={{maxWidth:'80%',padding:12,borderRadius:t.radius.bubble,backgroundColor:own?t.sharedSoft:t.surface}}><Text selectable style={{fontSize:16,lineHeight:25,color:t.text}}>{message.plainText}</Text>{message.fallback&&<Label muted>部分内容暂不支持，可在“我的”检查更新。</Label>}{message.attachments.map(file=><FileRow key={file.id} file={file} download={()=>download(file)}/>)}{message.status==='sending'&&<Label muted>发送中…</Label>}{message.status==='failed'&&<><Notice text={message.error??'发送失败'}/><Button title="重试发送" secondary onPress={retry}/></>}</View></View>;}
export function ChatScreen({id,runtime,transfers,details}:{id:string;runtime:Runtime;transfers:Transfers;details:()=>void}){
  const t=useTheme(),insets=useSafeAreaInsets();const navigation=useNavigation();const conversation=useWorkspace(s=>s.conversations[id]);const messages=useWorkspace(s=>s.messages[id]??emptyMessages);const draft=useWorkspace(s=>s.drafts[id]??'');const connection=useWorkspace(s=>s.connection);const [loading,setLoading]=useState(true),[error,setError]=useState(''),[hasOlder,setHasOlder]=useState(true),[progress,setProgress]=useState('');const list=useRef<FlatList<Message>>(null);const nearBottom=useRef(true);const [newMessages,setNewMessages]=useState(false);
  const load=useCallback(async()=>{setLoading(true);try{await runtime.open(id);}catch(e){setError(errorText(e));}finally{setLoading(false);}},[id,runtime]);useEffect(()=>{void load();},[load]);
  useLayoutEffect(()=>{navigation.setOptions({title:conversation?.displayTitle??'会话',headerRight:()=><Pressable accessibilityRole="button" accessibilityLabel="会话详情" onPress={details} style={{minWidth:t.hit,minHeight:t.hit,alignItems:'center',justifyContent:'center',paddingHorizontal:8}}><Text style={{color:t.shared,fontWeight:'600'}}>详情</Text></Pressable>});},[conversation?.displayTitle,details,navigation,t.hit,t.shared]);
  useEffect(()=>{if(nearBottom.current)list.current?.scrollToEnd({animated:false});else setNewMessages(true);const last=messages.at(-1);if(last&&!last.status&&nearBottom.current&&AppState.currentState==='active')void runtime.markRead(id,last.id).catch(()=>undefined);},[messages,id,runtime]);
  const send=(existing?:Message)=>{setError('');nearBottom.current=true;void runtime.send(id,draft,existing).catch(e=>setError(errorText(e)));};
  return <KeyboardAvoidingView behavior="padding" style={[styles.page,{backgroundColor:t.bg}]}>{connection!=='已连接'&&<InlineFeedback text={connection} tone="warning"/>}<Notice text={error||progress}/>{loading&&<Loading/>}<FlatList ref={list} data={messages} keyExtractor={m=>m.id} keyboardShouldPersistTaps="handled" onScroll={e=>{const {contentOffset,layoutMeasurement,contentSize}=e.nativeEvent;nearBottom.current=contentSize.height-contentOffset.y-layoutMeasurement.height<100;if(nearBottom.current)setNewMessages(false);}} scrollEventThrottle={100} onContentSizeChange={()=>{if(nearBottom.current)list.current?.scrollToEnd({animated:false});}} ListHeaderComponent={hasOlder&&messages.length>0?<Button title="加载更早消息" secondary onPress={()=>{void runtime.messages(id,messages[0]?.id).then(count=>setHasOlder(count===50)).catch(e=>setError(errorText(e)));}}/>:null} ListEmptyComponent={!loading?<Empty text="还没有消息"/>:null} renderItem={({item})=><MessageRow message={item} retry={()=>send(item)} download={file=>{const api=runtime.api;if(api)void transfers.download(api,useWorkspace.getState().accountKey,file).catch(e=>setError(errorText(e)));}}/>}/>{newMessages&&<Button title="回到最新" secondary onPress={()=>{nearBottom.current=true;setNewMessages(false);list.current?.scrollToEnd();}}/>}{conversation?.capabilities.canSendMessage?<View style={{padding:12,paddingBottom:Math.max(insets.bottom,12),gap:8,borderTopWidth:StyleSheet.hairlineWidth,borderTopColor:t.line,backgroundColor:t.bg}}><Input accessibilityLabel="消息" multiline placeholder="发送消息" value={draft} onChangeText={text=>runtime.draft(id,text)} style={{maxHeight:140,borderRadius:t.radius.input}}/><View style={styles.actions}><Button title="文件" secondary disabled={!conversation.capabilities.canUploadFile||!!progress} onPress={()=>{const api=runtime.api,key=useWorkspace.getState().accountKey;if(!api)return;void transfers.choose(key,id).then(async task=>{if(!task)return;setProgress('准备上传…');const file=await transfers.run(api,key,task,n=>setProgress(`上传 ${Math.round(n*100)}%`));if(file)await runtime.send(id,'',undefined,file.id);}).catch(e=>setError(errorText(e))).finally(()=>setProgress(''));}}/><Button title="发送" disabled={!draft.trim()} onPress={()=>send()}/></View></View>:<Empty text="当前会话不可发送消息"/>}</KeyboardAvoidingView>;
}
const emptyMessages:Message[]=[];
export function DetailsScreen({id,runtime}:{id:string;runtime:Runtime}){const c=useWorkspace(s=>s.conversations[id]);const t=useTheme();const [error,setError]=useState('');return <ScrollView style={{backgroundColor:t.bg}} contentContainerStyle={styles.content}><Text style={[styles.section,{color:t.text}]}>{c?.displayTitle}</Text><Label>{c?.retentionText}</Label><Label muted>共享空间会保存聊天和文件。</Label><Label>消息提醒</Label><View style={styles.actions}>{(['all','mentions','muted'] as const).map((level,i)=><Button key={level} title={['所有消息','仅提到我','免打扰'][i]??level} secondary={c?.notificationLevel!==level} onPress={()=>void runtime.notification(id,level).catch(e=>setError(errorText(e)))}/>)}</View><Notice text={error}/><Label>会话成员</Label>{c?.members.map(m=><Label key={m.id}>{m.displayName}</Label>)}</ScrollView>;}
export function FilesScreen({runtime,transfers}:{runtime:Runtime;transfers:Transfers}){const t=useTheme();const files=useWorkspace(s=>s.files);const key=useWorkspace(s=>s.accountKey);const permission=useWorkspace(s=>s.bootstrap?.permissions.canUpload);const [query,setQuery]=useState(''),[error,setError]=useState(''),[progress,setProgress]=useState(''),[revision,setRevision]=useState(0);const refresh=async()=>{if(!runtime.api)return;const r=await runtime.api.json(`/api/workspace/files?q=${encodeURIComponent(query)}`,z.object({files:z.array(attachmentSchema)}));useWorkspace.setState({files:r.files});};const run=async(task:ReturnType<Transfers['tasks']>[number])=>{if(!runtime.api)return;setProgress('上传中');try{await transfers.run(runtime.api,key,task,n=>setProgress(`上传 ${Math.round(n*100)}%`));await refresh();}catch(e){setError(errorText(e));}finally{setProgress('');setRevision(v=>v+1);}};return <View style={[styles.page,{backgroundColor:t.bg}]}><AppHeader title="文件" subtitle="文件库上传不会自动发到某个会话" includeTopInset/><ScrollView contentContainerStyle={styles.content}><Input accessibilityLabel="查找已加载的文件" placeholder="查找已加载的文件" value={query} onChangeText={setQuery}/><View style={styles.actions}><Button title="搜索" secondary onPress={()=>void refresh().catch(e=>setError(errorText(e)))}/><Button title="上传文件" disabled={!permission||!!progress} onPress={()=>void transfers.choose(key).then(task=>task&&run(task)).catch(e=>setError(errorText(e)))}/></View><Notice text={error||progress}/>{files.filter(f=>f.fileName.includes(query)).map(file=><FileRow key={file.id} file={file} download={()=>{if(runtime.api)void transfers.download(runtime.api,key,file).catch(e=>setError(errorText(e)));}}/>)}{!files.length&&<Empty text="还没有文件"/>}<Text style={{color:t.muted}}>上传任务</Text><View key={revision}>{transfers.tasks(key).filter(task=>!task.complete).map(task=><View key={task.id} style={{gap:8,paddingVertical:8}}><Label>{task.fileName}</Label><View style={styles.actions}><Button title="继续" secondary disabled={!!progress} onPress={()=>void run(task)}/><Button title="暂停" secondary onPress={()=>transfers.pause(task.id)}/><Button title="取消" secondary disabled={!!progress} onPress={()=>{if(runtime.api)void transfers.cancel(runtime.api,key,task).then(()=>setRevision(v=>v+1)).catch(e=>setError(errorText(e)));}}/></View></View>)}</View></ScrollView></View>;}
function FileRow({file,download}:{file:Attachment;download:()=>void}){const t=useTheme();return <View style={[styles.row,{borderColor:t.line}]}><Text numberOfLines={2} style={{color:t.text,fontSize:16}}>{file.fileName}</Text><Label muted>{Math.ceil(file.byteSize/1024)} KB · {file.status==='available'?'可下载':'暂不可用'}</Label><Button title="下载并保存" secondary disabled={!file.capabilities.canDownload} onPress={download}/></View>;}
export function MembersScreen({runtime,open}:{runtime:Runtime;open:(id:string)=>void}){const members=useWorkspace(s=>s.bootstrap?.members??[]);const [items,setItems]=useState(members),[query,setQuery]=useState(''),[error,setError]=useState('');const t=useTheme();return <View style={[styles.page,{backgroundColor:t.bg}]}><AppHeader title="成员" subtitle="可见联系人范围由服务端决定" includeTopInset/><View style={styles.content}><Input accessibilityLabel="查找可见成员" placeholder="查找可见成员" value={query} onChangeText={setQuery}/><Button title="搜索" secondary onPress={()=>{if(runtime.api)void runtime.api.json(`/api/workspace/members?q=${encodeURIComponent(query)}`,z.object({members:z.array(memberSchema)})).then(r=>setItems(r.members)).catch(e=>setError(errorText(e)));}}/><Notice text={error}/></View><FlatList data={items} keyExtractor={m=>m.id} ListEmptyComponent={<Empty text="当前范围内没有匹配成员"/>} renderItem={({item})=><View style={[styles.row,{borderColor:t.line}]}><Label>{item.displayName}{item.kind==='bot'?' · Bot':''}</Label>{item.capabilities.canStartDirectConversation&&<Button title="发起私聊" secondary onPress={()=>void runtime.direct(item.id).then(open).catch(e=>setError(errorText(e)))}/>}</View>}/></View>;}
export function UpdatePrompt({runtime}:{runtime:Runtime}){const policy=useWorkspace(s=>s.policy);const [deferred,setDeferred]=useState('');const t=useTheme();if(!policy)return null;const decision=updateDecision(policy,installed);const dismissed=z.number().catch(0).parse(cache.get(`defer:${policy.latest.releaseId}`)??0);if(decision==='none'||(decision!=='forced'&&(deferred===policy.latest.releaseId||dismissed>Date.now())))return null;return <View accessibilityViewIsModal={decision==='forced'} style={{padding:16,gap:12,backgroundColor:t.surface}}><Text style={{fontSize:18,fontWeight:'600',color:t.text}}>{decision==='forced'?'请更新后继续使用':decision==='strong'?'建议尽快更新':'发现新版本'}</Text><Label>{policy.latest.releaseNotes.join('\n')||`可用版本 ${policy.latest.appVersion}`}</Label>{policy.apkUrl?<Button title="下载更新" onPress={()=>void Linking.openURL(policy.apkUrl!)}/>:<Label muted>安装包暂未发布，请联系空间维护者。</Label>}<Button title="重新检查" secondary onPress={()=>void runtime.checkPolicy()}/>{decision!=='forced'&&<Button title="稍后提醒" secondary onPress={()=>{cache.set(`defer:${policy.latest.releaseId}`,Date.now()+86400000);setDeferred(policy.latest.releaseId);}}/>}</View>;}
