const assert = require('node:assert/strict');
const { readFileSync } = require('node:fs');
const { join } = require('node:path');
const { test } = require('node:test');
const { addGradleDependencies, installInMainApplication, CRONET_SOURCE } = require('./android-cronet.cjs');

const gradle = `dependencies {
    implementation("com.facebook.react:react-android")
    implementation("com.facebook.react:hermes-android")
}`;

const main = `class MainApplication : Application(), ReactApplication {
  override fun onCreate() {
    super.onCreate()
    loadReactNative(this)
  }
}
`;

test('prebuild adds embedded Cronet dependencies once', () => {
  const result = addGradleDependencies(gradle);
  assert.match(result, /cronet-embedded:143\.7445\.0/);
  assert.match(result, /cronet-okhttp:0\.1\.1/);
  assert.equal(addGradleDependencies(result), result);
});

test('prebuild installs Cronet before React Native starts', () => {
  const result = installInMainApplication(main);
  assert.match(result, /super\.onCreate\(\)\n    CronetNetworking\.install\(this\)/);
  assert.ok(result.indexOf('CronetNetworking.install(this)') < result.indexOf('loadReactNative(this)'));
  assert.equal(installInMainApplication(result), result);
});

test('prebuild is idempotent on the checked-in Android project', () => {
  const gradleFile = readFileSync(join(__dirname, '../android/app/build.gradle'), 'utf8');
  const mainFile = readFileSync(join(__dirname, '../android/app/src/main/java/com/timestarry/duallane/MainApplication.kt'), 'utf8');
  assert.equal(addGradleDependencies(gradleFile), gradleFile);
  assert.equal(installInMainApplication(mainFile), mainFile);
});

test('generated transport bypasses Cronet only for a complete WebSocket upgrade', () => {
  assert.match(CRONET_SOURCE, /headerContainsToken\(request, "Upgrade", "websocket"\) &&\s+headerContainsToken\(request, "Connection", "upgrade"\)/);
  assert.match(CRONET_SOURCE, /if \(isWebSocketUpgrade\) chain\.proceed\(request\) else cronet\.intercept\(chain\)/);
  assert.match(CRONET_SOURCE, /request\.headers\(name\)\.any \{ value ->\s+value\.split\(','\)\.any \{ it\.trim\(\)\.equals\(token, ignoreCase = true\) \}/);
  assert.equal((CRONET_SOURCE.match(/CronetInterceptor\.newBuilder\(engine\)\.build\(\)/g) ?? []).length, 1);
  assert.match(CRONET_SOURCE, /val cronet = CronetInterceptor\.newBuilder\(engine\)\.build\(\)/);
  assert.match(CRONET_SOURCE, /\.addInterceptor\(webSocketAwareInterceptor\(cronet\)\)/);
  assert.match(CRONET_SOURCE, /\.enableQuic\(true\)/);
  assert.match(CRONET_SOURCE, /\.enableHttp2\(true\)/);
  assert.doesNotMatch(CRONET_SOURCE, /hostnameVerifier|sslSocketFactory/);
});

test('checked-in Cronet transport is exactly the source generated by prebuild', () => {
  const nativeFile = readFileSync(join(__dirname, '../android/app/src/main/java/com/timestarry/duallane/CronetNetworking.kt'), 'utf8');
  assert.equal(nativeFile.replace(/\r\n/g, '\n'), CRONET_SOURCE.replace(/\r\n/g, '\n'));
});
